### ISSUE TITLE
Patching fails when source directory contains space

### ISSUE THREAD

**Issue by kylethebaker** [wix/react-native-repackager#6]
Here is the error that gets thrown (from the shell out to `patch`)

```
/bin/sh: /Users/kbaker1/Code/Directory: No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: patch --reverse --strip 1 --directory node_modules/react-native < /Users/kbaker1/Code/Directory With Space/node_modules/react-native-repackager/repackagerRN51Setup.patch
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.execSync (/Users/kbaker1/Code/Directory With Space/node_modules/shell-utils/src/exec.js:8:6)
    at patch (/Users/kbaker1/Code/Directory With Space/node_modules/react-native-repackager/repackager.js:49:8)
    at setup (/Users/kbaker1/Code/Directory With Space/node_modules/react-native-repackager/repackager.js:29:3)
    at run (/Users/kbaker1/Code/Directory With Space/node_modules/react-native-repackager/repackager.js:19:5)
    at Object.<anonymous> (/Users/kbaker1/Code/Directory With Space/node_modules/react-native-repackager/repackager.js:14:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

```

The full path to the project directory is `/Users/kbaker1/Code/Directory With Space/` but you can see on the first line of the error that it is trying to read from `/Users/kbaker1/Code/Directory`

The easiest fix for this is to wrap the .patch path with quotes.

**Comment by DanielZlotin** [comment]
`0.51.1`
